### ISSUE TITLE
Problem using UART2 (/dev/ttyS2) with NanoPi NEO Air

### ISSUE THREAD

**Issue by ezamp** [friendlyarm/npi-config#1]
Hello,
I'm using a NanoPi NEO Air with debian (kernel 4.11.2) and I have some problem with UART2.

I try to enable the UART 1 and 2 with "sudo npi-config" utility. After reboot, the UART1(/dev/ttyS1) worked properly but UART2(/dev/ttyS2) is not working.

**Comment by lesto** [comment]
same problem with NEO2 but only for UART2 RX, but disabling all the SPI and I2C interface will make it work. I suspect is one of the SPI that take over the UART2 RX pin (gpio readall show "OUT" instead of "ALT5", disabling the interface until become "OFF" and then enabling UART2 work properly)

**Comment by lawrencetg** [comment]
Thanks for the feedback, we have fixed it.
